default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] || 'localhost' %> 
  database: <%= ENV['DB_NAME'] || 'booklydb'%>
  username: <%= ENV['DB_USER'] || 'postgres'%> 
  password: <%= ENV['DB_PASSWORD'] || 'postgres'%> 


development:
  <<: *default

production:
  <<: *default
  # database: mock_delivery_production
  # username: mock_delivery
  # password: <%= ENV["MOCK_DELIVERY_DATABASE_PASSWORD"] %>
